name: DsMenu
version: '${project.version}'
main: ru.dscraft.dsmenu.DsMenuPlugin
api-version: '1.21'
author: DestroyCraft
description: Главное меню /menu и меню привилегий /donate

commands:
  menu:
    description: Главное меню
    usage: /menu
    aliases: [меню]
  donate:
    description: Меню привилегий
    usage: /donate
    aliases: [donat, privileges, привилегии]
  warps:
    description: Меню телепортов
    usage: /warps
  dsmenu:
    description: Перезагрузка конфига меню
    usage: /dsmenu reload
    permission: dsmenu.admin

permissions:
  dsmenu.admin:
    default: op
