name: MediaItems
version: '1.0'
main: ru.dscraft.mediaitems.MediaItemsPlugin
api-version: '1.21'
author: loserwrld
description: НПС-торговцы сетами и мечами с бафами (обмен ресурсов), /itemnpc create <магазин>
softdepend: [FancyNpcs, HeadDatabase, Multiverse-Core]
commands:
  itemnpc:
    description: НПС-торговцы предметами
    usage: /itemnpc <create|remove|list|movehere|give|shops|reload>
    permission: mediaitems.admin
  upgrade:
    description: Наковальня для улучшения сетов
    aliases: [anvil]
permissions:
  mediaitems.staffmenu:
    description: Доступ к /menu items (кроме групп из staff-menu.groups)
    default: op
  mediaitems.admin:
    default: op
  mediaitems.titles.customcolor:
    default: true
