name: build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - run: mvn -B -f destroypvp/pom.xml package
      - run: mvn -B -f destroyskypvp/pom.xml package
      - run: mvn -B -f mediaeconomy/pom.xml package
